FROM python:3.11

WORKDIR /frontend

# Copie les fichiers frontend
COPY frontend /frontend

# Copie le requirements.txt à la racine (si commun)
COPY requirements.txt /frontend/requirements.txt

# Installation
RUN pip install --no-cache-dir -r /frontend/requirements.txt

# Commande de lancement
CMD ["streamlit", "run", "app.py", "--server.port=80", "--server.address=0.0.0.0","--server.baseUrlPath=/smartpro"]
