FROM python:3.11

WORKDIR /app/app

# Copie le code du backend
COPY ./backend /app

# Copie le requirements.txt situé à la racine
COPY requirements.txt /app/requirements.txt

# Installation des dépendances
RUN pip install --no-cache-dir -r /app/requirements.txt

# Commande de lancement
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]
