FROM python:3.11

WORKDIR /app

# Copie le code du backend
COPY ./backend/app /app

# Copie le requirements.txt situé à la racine
COPY requirements.txt /app/requirements.txt
#✅ Ajout du dossier de travail dans le PYTHONPATH
ENV PYTHONPATH=/app

# Installation des dépendances
RUN pip install --no-cache-dir -r /app/requirements.txt

# Commande de lancement
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]
