name: Deploy FastAPI Backend

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/deploy-backend.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        
      - name: Create ECR repository if it doesn't exist
        run: |
          aws ecr describe-repositories --repository-names smartbank-backend \
          || aws ecr create-repository --repository-name smartbank-backend
      - name: Build and push Docker image
        env:
          ECR_REPOSITORY: ${{ vars.ECR_REPOSITORY }}
          ACCOUNT_ID: ${{ vars.ACCOUNT_ID }}
          AWS_REGION: ${{ vars.AWS_REGION }}
        run: |
          IMAGE_TAG=backend-${{ github.sha }}
          IMAGE_URI=${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY}:${IMAGE_TAG}
          
          docker build -t $IMAGE_URI -f backend/app/Dockerfile.backend .
          docker push $IMAGE_URI

        
      - name: Register ECS Task Definition
        id: register-task
        env:
          IMAGE_TAG: frontend-${{ github.sha }}
          ECR_REPOSITORY: smartbank-backend
          AWS_REGION: ${{ vars.AWS_REGION }}
          ACCOUNT_ID: ${{ vars.ACCOUNT_ID }}
        run: |
          IMAGE_URI=${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${ECR_REPOSITORY}:${IMAGE_TAG}
          sed "s|{{IMAGE_URI}}|$IMAGE_URI|g; s|{{ACCOUNT_ID}}|$ACCOUNT_ID|g" .github/task-definitions/frontend.json > backend-task.json

          TASK_DEF_ARN=$(aws ecs register-task-definition --cli-input-json file://backend-task.json --query 'taskDefinition.taskDefinitionArn' --output text)
          echo "TASK_DEF_ARN=$TASK_DEF_ARN" >> $GITHUB_ENV
 
      - name: Authorize security group ingress (port 8000)
        env:
          SECURITY_GROUP_ID: ${{ vars.SECURITY_GROUP_ID }}
        run: |
          aws ec2 authorize-security-group-ingress \
            --group-id $SECURITY_GROUP_ID \
            --protocol tcp \
            --port 8000 \
            --cidr 0.0.0.0/0 || echo "Ingress rule already exists or failed silently"
      - name: Create ECS Service (if not exists)
        env:
          CLUSTER_NAME: ${{ vars.CLUSTER_NAME }}
          SERVICE_NAME: ${{ vars.SERVICE_NAME_BACKEND }}
          SUBNET_1: ${{ vars.SUBNET_1 }}
          SUBNET_2: ${{ vars.SUBNET_2 }}
          SECURITY_GROUP_ID: ${{ vars.SECURITY_GROUP_ID }}
        run: |
          SERVICE_EXISTS=$(aws ecs describe-services \
            --cluster $CLUSTER_NAME \
            --services $SERVICE_NAME \
            --query "services[0].status" \
            --output text 2>/dev/null || echo "MISSING")

          if [ "$SERVICE_EXISTS" = "MISSING" ]; then
            echo "Creating ECS service: $SERVICE_NAME"
            aws ecs create-service \
              --cluster $CLUSTER_NAME \
              --service-name $SERVICE_NAME \
              --launch-type FARGATE \
              --task-definition smartbank-backend-task \
              --desired-count 1 \
              --network-configuration "awsvpcConfiguration={subnets=[\"$SUBNET_1\",\"$SUBNET_2\"],securityGroups=[\"$SECURITY_GROUP_ID\"],assignPublicIp=\"ENABLED\"}" \
              --scheduling-strategy REPLICA
          else
            echo "Service $SERVICE_NAME already exists — skipping creation"
          fi      
      - name: Update ECS Service with latest task definition
        env:
          CLUSTER_NAME: ${{ vars.CLUSTER_NAME }}
          SERVICE_NAME: ${{ vars.SERVICE_NAME_BACKEND }}
        run: |
          echo "Using task definition: $TASK_DEF_ARN"

          aws ecs update-service \
            --cluster "$CLUSTER_NAME" \
            --service "$SERVICE_NAME" \
            --task-definition "$TASK_DEF_ARN" \
            --force-new-deployment

